# Generated by Django 2.2.5 on 2022-03-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220228_2059'),
        ('reviews', '0002_auto_20220228_2100'),
    ]

    operations = [
    ]
